channels:
  - defaults
  - conda-forge
  - nodefaults
dependencies:
  - python
  - numpy<1.20.0
  - scipy
  - scikit-learn<0.23.0
  - setuptools
  - marisa-trie
  - nltk
  - singledispatch
  - pybktree
  - pip
  - pip:
    - "git+ssh://git@github.com/sverchkov/MetaSRA-pipeline@pkg"
